create table if not exists public.users (
    id bigint generated by default as identity primary key,
    username text unique not null,
    password text not null,
    role text not null default 'user',
    created_at timestamptz not null default now()
);

alter table public.users enable row level security;

-- Server-side service-role access is used by Flask. Do not expose that key in browser code.
