create table if not exists public.users (
    id bigint generated by default as identity primary key,
    username text unique not null,
    password text not null,
    role text not null default 'user',
    created_at timestamptz not null default now()
);

alter table public.users enable row level security;

create unique index if not exists one_admin_account
on public.users (role)
where role = 'admin';

-- Server-side service-role access is used by Flask. Do not expose that key in browser code.
